[project]
name = "medscraper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "duckdb>=1.4.4",
    "numpy>=2.4.2",
    "pandas>=3.0.1",
]
